{{- if and (not .Values.existingSecret) (or .Values.secrets.GROQ_API_KEY .Values.secrets.GOOGLE_API_KEY) }}
apiVersion: v1
kind: Secret
metadata:
  name: aicouncil-secrets
  labels:
    app: aicouncil
type: Opaque
stringData:
  {{- if .Values.secrets.GROQ_API_KEY }}
  GROQ_API_KEY: {{ .Values.secrets.GROQ_API_KEY | quote }}
  {{- end }}
  {{- if .Values.secrets.GOOGLE_API_KEY }}
  GOOGLE_API_KEY: {{ .Values.secrets.GOOGLE_API_KEY | quote }}
  {{- end }}
{{- end }}
