apiVersion: v1
kind: Service
metadata:
  name: aicouncil
  labels:
    app: aicouncil
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: aicouncil

